In [1]:
# Numpyのアレイを利用
import numpy as np

# Pythonのリスト型から変換して作ることができる。
my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)

In [2]:
# アレイを表示する
my_array1

array([1, 2, 3, 4])

In [3]:
# 別のアレイを作って
my_list2 = [11,22,33,44]

# リストのリストを作成
my_lists = [my_list1,my_list2]

# これを使って、多次元のアレイを作れる
my_array2 = np.array(my_lists)

my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [4]:
# アレイのサイズを調べる
my_array2.shape

(2, 4)

In [5]:
# アレイのデータ型を調べる
my_array2.dtype

dtype('int64')

In [6]:
# 特別なアレイを作る

#すべての要素が０
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
my_zeros_array = np.zeros(5)

In [8]:
my_zeros_array.dtype

dtype('float64')

In [9]:
#すべての要素が1
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# 空っぽのアレイ

np.empty(5)
np.empty((3,4))

array([[1.72723371e-077, 1.72723371e-077, 7.41098469e-323,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [11]:
#単位行列I（dentity array）
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# arange関数
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.arrange(5)

AttributeError: module 'numpy' has no attribute 'arrange'

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(5,10,2)

array([5, 7, 9])

In [20]:
np.arange(5,100,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
       73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [21]:
np.arrange(1,14)

AttributeError: module 'numpy' has no attribute 'arrange'

In [22]:
np.arange(1,14)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])